# white eye for 'dark' theme and black eye for 'light' theme
theme: dark

# language for notifications: [en - english (default), ru - russian, ua - ukrainian]
language: ru

# speaking-eye analyzes activity only for detailed_apps and distracting_apps
# wm_name/tab are looked up with a regular expression so you can specify only part of the name
# speaking-eye takes first match for app info so write more specific apps higher

apps:
  detailed:
    - Jupyter Notebook:
        wm_name: Chromium
        tab: Jupyter Notebook
    - Google Meet:
        wm_name: Chromium
        tab: Meet -
    - Jira Kanban:
        wm_name: Chromium
        tab: Agile Board - JIRA
    - Internet:
        wm_name: Chromium|Firefox
    - IDE:
        wm_name: jetbrains-pycharm|jetbrains-idea|jetbrains-datagrip
    - Terminal:
        wm_name: Gnome-terminal|X-terminal-emulator
    - Slack:
        wm_name: Slack
    - Spotify:
        wm_name: Spotify

  distracting:
    - Telegram:
        wm_name: Telegram
    - YouTube:
        wm_name: Chromium|Firefox
        tab: YouTube

time_limits:
  work_time_hours: 9
  breaks_interval_hours: 3
  distracting_apps_mins: 20

# service with reports about your working days
# will be run on http://localhost:{port}/ after speaking-eye starting
report_server:
  port: 3838
