# white eye for 'dark' theme and black eye for 'light' theme
theme: dark

# speaking-eye analyzes activity only for detailed_apps and distracting_apps
# wm_name/tab are looked up with a regular expression so you can specify only part of the name
# speaking-eye takes first match for app info so write more specific apps higher

apps:
  detailed:
    - Jupyter Notebook:
        wm_name: Chromium|Firefox
        tab: Jupyter Notebook
    - Internet:
        wm_name: Chromium|Firefox
    - IDE:
        wm_name: jetbrains-pycharm|jetbrains-idea
    - Terminal:
        wm_name: Terminal

  distracting:
    - Telegram:
        wm_name: Telegram
    - YouTube:
        wm_name: Chromium|Firefox
        tab: YouTube

time_limits:
  work_time_hours: 9
  breaks_interval_hours: 2
  distracting_apps_mins: 5
